In [1]:
import torch

b, c, h, w = 1, 1, 2, 2
d4_channel = torch.rand(b, c, h, w)
print(d4_channel)
print(d4_channel.shape)

tensor([[[[0.3106, 0.8038],
          [0.6825, 0.3572]]]])
torch.Size([1, 1, 2, 2])


In [2]:
viewed_channel = d4_channel.view(b, h * w, c)
print(viewed_channel)
print(viewed_channel.shape)

tensor([[[0.3106],
         [0.8038],
         [0.6825],
         [0.3572]]])
torch.Size([1, 4, 1])


In [3]:
permuted_channel = viewed_channel.permute(0, 2, 1)
print(permuted_channel)
print(permuted_channel.shape)

tensor([[[0.3106, 0.8038, 0.6825, 0.3572]]])
torch.Size([1, 1, 4])


In [4]:
permuted_channel = viewed_channel.permute(0, 2, 1)
print(permuted_channel)
print(permuted_channel.shape)

tensor([[[0.3106, 0.8038, 0.6825, 0.3572]]])
torch.Size([1, 1, 4])


In [5]:
flatten_channel = torch.flatten(permuted_channel, start_dim=0)
print(flatten_channel)
print(flatten_channel.shape)

tensor([0.3106, 0.8038, 0.6825, 0.3572])
torch.Size([4])
